language: node_js

node_js:
  - stable
  - lts/carbon
  - lts/boron

env:
  - EGG_VERSION=1
  - EGG_VERSION=2

matrix:
  exclude:
    - node_js: lts/boron
      env: EGG_VERSION=2

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
  - npm install egg@$EGG_VERSION
